[package]
name = "nu_plugin_image"
license = "MIT"
authors = ["Motalleb Fallahnezhad <fmotalleb@gmail.com>"]
keywords = ["nushell", "image", "render", "plugin"]
homepage = "https://github.com/FMotalleb/nu_plugin_image"
repository = "https://github.com/FMotalleb/nu_plugin_image"
description = "A nushell plugin to open png images in the shell and save ansi string as images (like tables or ...)"
version = "1.0.0"
edition = "2021"
readme = "README.md"

[dependencies]
nu-plugin = "0.87.1"
nu-protocol = { version = "0.87.1", features = ["plugin"] }
image = "0.24.7"
terminal_size = "0.3.0"
getopts = "0.2.21"
unicode-segmentation = "1.8.0"
log = "0.4.14"
simple_logger = "4.3.0"

clap = { version = "4", features = ["derive"] }
imageproc = "0.23"
include-flate = "0.3"
rusttype = "0.9"
vte = "0.13"
