on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 */2 * *' 
  
name: Update dependencies
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
        -   name: Setup Nushell
            uses: hustcer/setup-nu@main
            with:
              version: "*"
        -   uses: actions/checkout@v2
        -   name: prepare
            shell: nu -c {0}
            run: |
              http get https://raw.githubusercontent.com/FMotalleb/nushell_sync_script/refs/heads/main/bump_dependencies.nu
                | save /tmp/update.nu
              nu /tmp/update.nu
        -   uses: EndBug/add-and-commit@v9 
            
            with:
                author_name: GitHub-Action
