---
on: workflow_dispatch
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login
      run: cargo login ${{ secrets.CARGO_KEY }}

    - name: Push
      run: cargo publish
    
